### ISSUE TITLE
PC Miner UnicodeEncodeError on Raspberry Pi

### ISSUE THREAD

**Issue by link3384** [duino-coin/duino-coin#983] opened 2021-09-08 21:46 UTC
Hello,
I am new to this whole concept so i am really sorry in advance if i make any mistake.
I try to start mining with my Raspberry Pi, i did all the steps as instructed but when i run PC_Miner.py it shows me the following error message:

```
pi@raspberrypi:~/duino-coin $ python3 PC_Miner.py
Xxhash is not installed - this mining algorithm will be disabled
Traceback (most recent call last):
  File "PC_Miner.py", line 804, in <module>
    Miner.greeting()
  File "PC_Miner.py", line 399, in greeting
    + Fore.RESET + "2019-2021")
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "/usr/lib/python3/dist-packages/colorama/ansitowin32.py", line 143, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2016' in position 11: ordinal not in range(256)
pi@raspberrypi:~/duino-coin $ 
```
Am i doing something wrong?
Thank you in advance for your help.

**Comment by BastelPichi** [comment] 2021-09-10 14:28
This somehow seems to be caused by a bad charcter in the translation. Could you maybe try changing your raspberry pi language to english for now?

**Comment by revoxhere** [comment] 2021-09-26 19:27
Hello, are you still facing this issue with the newest versions?

**Comment by link3384** [comment] 2021-09-29 16:14
Hello,
I solved the problem.
I just had to put UTF-8 at character set at locale.
Thank you very much for your help!

**Comment by gsrbr** [comment] 2021-09-29 16:52
Hello @link3384 , we are very happy :smile: to hear that your issue has been resolved:heavy_check_mark:, would you please close this issue

**Closed as completed** 2021-09-29 16:57 UTC
Labels: bug
