### ISSUE TITLE
Cant pass the 100 share.

### ISSUE THREAD

**Issue by Axoluto** [duino-coin/duino-coin#1754] opened 2024-01-24 05:58 UTC
Im mining on a arduino pro micro with my mac as an interface and running avr_miner.py.
I can never pass the 100 shares.
![Captura de ecrã 2024-01-24, às 05 29 39](https://github.com/revoxhere/duino-coin/assets/30011483/e6de24cf-740f-40d4-9f6d-8d8a253820c8)
 Can somebody please give me some clue of where to begin?

Thanks in advance.

**Comment by revoxhere** [comment] 2024-01-24 06:50
Duplicate of #1733.

**Closed as not planned by revoxhere** 2024-01-24 06:50 UTC

**Comment by Axoluto** [comment] 2024-01-24 15:25
THanks @revoxhere, Solved with the solution in #1733. 
Thanks again to all who make this possible.
