### ISSUE TITLE
No miners detected problam

### ISSUE THREAD

**Issue by hashArun** [duino-coin/duino-coin#833] opened 2021-08-19 03:43 UTC
hi this issues my duco balance not increased but my miners are  working, please  check the problam

**Comment by mondorescue1** [comment] 2021-08-19 05:14
Same for me.

**Comment by Tech1k** [comment] 2021-08-19 06:04
I'll let @revoxhere take over this issue when he's online again. Until then, could you be more specific in what is happening?

**Comment by mondorescue1** [comment] 2021-08-19 06:17
The web wallet doesn't show my miners. So I decided to update my miners to a new version. Serial log of my esp8266 show that it is working fine. But the web wallet doesn't recognize my miners. The update also doesn't solve the problem.

**Comment by Tech1k** [comment] 2021-08-19 06:18
Interesting, this could be a server error, is it possible for you to post your logs here for me to take a look?

**Comment by LordKlaus** [comment] 2021-08-19 07:14
I have the same problem. I mining DUCOs with AVR and ESP32 and ESP8266. Only some ESP32 and 8266 are shown in the webwallet, the rest of them and all the AVRs aren't. And I'm sure are mining as I can see the records scrolling in the console.
Also tried to restart the mining with no luck. Apparenlty the mined quantity is increasing, so it appear to be a bug on the webwallet.

**Comment by hashArun** [comment] 2021-08-19 08:19
another problam pc miners not showing on my wallet hashrate but runing pc miner please check the problam

**Comment by revoxhere** [comment] 2021-08-19 08:48
I'll check what may be causing it, my guess is that thre's something wrong with removing inactive miners from the minerapi. Anyway, even if the miners aren't shown, earnings are still credited as they use a separate api

**Comment by redsun69** [comment] 2021-08-19 14:38
![image](https://user-images.githubusercontent.com/88141841/130087468-36d2172d-81c7-4f8c-9f9d-6f341bfec055.png)

me to... it's been 6 hours worker is running.. wallet stuck clam reward

**Comment by mondorescue1** [comment] 2021-08-22 06:14
Could it be that the problem is solved? All my miners are visible in web wallet since several days.
Best regards

**Comment by revoxhere** [comment] 2021-08-22 10:27
Yes, should be fixed

**Comment by hashArun** [comment] 2021-08-22 13:32
Problem solved thanks for developers

**Closed as completed** 2021-08-22 13:42 UTC
Labels: bug
