### ISSUE TITLE
ESP8266

### ISSUE THREAD

**Issue by romanmajorov** [duino-coin/duino-coin#1062] opened 2021-10-16 22:05 UTC
I can't run mining on the server. Is writing

esp8266_code:23:11: fatal error: ArduinoJson.h: There is no such file or directory

23 | #enable <ArduinoJson.h>

| ^~~~~~~~~~~~~~~

compilation is complete.

exit status 1

Arduino Json.h: There is no such file or directory

Arduino: 1.8.16 (Windows 7), Board: "NodeMCU 1.0 (ESP-12E module), 80 MHz, Flash, Disabled (new interrupts in OOM), Disabled, All SSL ciphers (most compatible), 32 KB cache+32 KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4 MB (FS:2 MB OTA:~1019 KB), 2, v2 Less memory, Disabled, No, Sketch only, 115200"

**Comment by revoxhere** [comment] 2021-10-17 09:17
Duplicate of https://github.com/revoxhere/duino-coin/issues/832

**Closed as completed by revoxhere** 2021-10-17 09:17 UTC
