### ISSUE TITLE
The Duino-coin main server is down

### ISSUE THREAD

**Issue by marcoduinocoin** [duino-coin/duino-coin#724] opened 2021-07-28 17:50 UTC
The Duino-coin main server is down, the web wallet can't not access, the mining speed is extremely slow. Kindly solve these deadly problems or the miners will be decreased since can't mining correctly.

**Comment by primitt** [comment] 2021-07-28 18:02
Kindly saying, revox is helping is family at the moment, but we are trying our best.

**Comment by marcoduinocoin** [comment] 2021-07-28 18:09
> Kindly saying, revox is helping is family at the moment, but we are trying our best.

I saw one of powerful users only can get less than 0.01 coins for 4 hours(50 miners as shown), that's really bad. Me and my friends are wanna stop our miners (more than 1000 machines) since can't mining correctly.

**Comment by marcoduinocoin** [comment] 2021-07-28 18:09
> Kindly saying, revox is helping is family at the moment, but we are trying our best.

I saw one of powerful users only can get less than 0.01 coins for 4 hours(50 miners as shown), that's really bad. Me and my friends are wanna stop our miners (more than 1000 machines) since can't mining correctly.

**Comment by revoxhere** [comment] 2021-07-28 18:10
1000 machines you say, interesting xD

**Comment by marcoduinocoin** [comment] 2021-07-28 18:10
oops 100

**Comment by revoxhere** [comment] 2021-07-28 18:11
![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
Have a nice day everyone. I'm not even doing anything until others stop being jerks

**Comment by marcoduinocoin** [comment] 2021-07-28 18:12
great, let's see on dogecoin page

**Comment by primitt** [comment] 2021-07-28 18:21
> ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> Have a nice day everyone. I'm not even doing anything until others stop being jerks

That is a beautiful picture (and the **fire** shoes)

**Comment by primitt** [comment] 2021-07-28 18:23
> great, let's see on dogecoin page

:what:

**Comment by marcoduinocoin** [comment] 2021-07-28 18:27
> > great, let's see on dogecoin page
> 
> :what:

relax, just joking :) duino-coin is my favorite, my old avr machines and old phones and some low power arduino boards are mining for duino-coin. hope will grow up and support my learning in the university.

**Comment by marcoduinocoin** [comment] 2021-07-28 18:34
my friends got 100 pcs of arduino boards and asking me how to use the board to mine some lucky duino-coins, we just use an old laptop to upload the script to the boards and running them in our computer room inside the university. the exchange rate of duino-coin is growing up slowly, and we're assumed we can buy an old benz after a few years when we all tranafer our duino-coins and collect together after a few years, although we still poor... maybe we can

**Comment by marcoduinocoin** [comment] 2021-07-28 18:36
> ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> Have a nice day everyone. I'm not even doing anything until others stop being jerks

our family also farming since 1980s

**Comment by primitt** [comment] 2021-07-28 18:41
ok?

**Comment by primitt** [comment] 2021-07-28 18:41
noice

**Comment by mrgh14** [comment] 2021-07-28 20:37
is it end of every things?!

**Comment by sys-256** [comment] 2021-07-28 20:46
> is it end of every things?!

No.

**Comment by marcoduinocoin** [comment] 2021-07-29 01:24
Nothing to worry. Just relax. Kindly wait for a few days.

**Comment by marcoduinocoin** [comment] 2021-07-29 01:30
no one succeeds over night, success belongs to those who are willing to start small and patiently work until their jug is filled.

**Comment by ekopesik** [comment] 2021-07-29 07:21
> ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> Have a nice day everyone. I'm not even doing anything until others stop being jerks

we are waiting for you brother

**Comment by ericddm** [comment] 2021-07-29 09:26
> ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> Have a nice day everyone. I'm not even doing anything until others stop being jerks 

just like my hometown,  it's really beautiful and I miss it. I have been other place for 7 months,  havn't seen my mom and dad for 7 months.

I come from Qingdao, Shandong Province,  China.

After typing these words,  I gonna buy a ticket

**Comment by marcoduinocoin** [comment] 2021-07-29 12:30
> > ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> > Have a nice day everyone. I'm not even doing anything until others stop being jerks
> 
> just like my hometown, it's really beautiful and I miss it. I have been other place for 7 months, havn't seen my mom and dad for 7 months.
> 
> I come from Qingdao, Shandong Province, China.
> 
> After typing these words, I gonna buy a ticket

China is a good place. I've been to Qingdao for travel with my family when I was 10. The transitional restaurants were great, still can't forget we had a BBQ dinner in the town.

**Comment by ericddm** [comment] 2021-07-30 07:40
> > > ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> > > Have a nice day everyone. I'm not even doing anything until others stop being jerks
> > 
> > just like my hometown, it's really beautiful and I miss it. I have been other place for 7 months, havn't seen my mom and dad for 7 months.
> > 
> > I come from Qingdao, Shandong Province, China.
> > 
> > After typing these words, I gonna buy a ticket
> 
> China is a good place. I've been to Qingdao for travel with my family when I was 10. The transitional restaurants were great, still can't forget we had a BBQ dinner in the town. 

thanks man. It's an honor for me to give you a great experience. Welcome to Qingdao. :)

**Comment by marcoduinocoin** [comment] 2021-07-30 14:42
> > > > ![IMG_20210728_201023875.jpg](https://user-images.githubusercontent.com/50244265/127374252-4fb2d4aa-c273-4c95-83f5-d050bb7b8d71.jpg)
> > > > Have a nice day everyone. I'm not even doing anything until others stop being jerks
> > > 
> > > 
> > > just like my hometown, it's really beautiful and I miss it. I have been other place for 7 months, havn't seen my mom and dad for 7 months.
> > > I come from Qingdao, Shandong Province, China.
> > > After typing these words, I gonna buy a ticket
> > 
> > 
> > China is a good place. I've been to Qingdao for travel with my family when I was 10. The transitional restaurants were great, still can't forget we had a BBQ dinner in the town.
> 
> thanks man. It's an honor for me to give you a great experience. Welcome to Qingdao. :)

Thanks bro. Hope you.and your family are always smiling and healthy.

**Comment by revoxhere** [comment] 2021-07-30 14:43
Really inspiring conversation out there :)

**Comment by marcoduinocoin** [comment] 2021-07-31 02:05
> Really inspiring conversation out there :)

Thanks Revox! You are the best. I just watched your videos on YouTube and started to mining the Duino-Coin in my university. The Duino-Coin is really awesome that able to mine on any kinds of electronic devices, especially the Arduino boards! 

Hope to try to mining with some ESP8266 boards with my homemade solar panel station in my farms.

**Comment by revoxhere** [comment] 2021-07-31 08:30
Cool, good luck with mining! Since the issue is fixed, I'm closing this thread for now

**Closed as completed by revoxhere** 2021-07-31 08:30 UTC
